name: 'Publish application'
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checkout the code
        - uses: actions/checkout@v2

        # Install .NET Core SDK
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 6.0.x
            include-prerelease: true

        # Replace base href
        - name: Replace Href base address
          run: sed -i 's/href=\"\/\"/href=\"\/MyBlog\/\"/' MyBlog/wwwroot/index.html

        # Duplicate index into 404.html
        - name: Copy index.html to 404.html
          run: cp MyBlog/wwwroot/index.html MyBlog/wwwroot/404.html

        # Run tests
        - name: Test
          run: dotnet test

        # Generate the website
        - name: Publish
          run: dotnet publish MyBlog/MyBlog.csproj --configuration Release

        # Publish the website
        - name: GitHub Pages action
          if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
          uses: peaceiris/actions-gh-pages@v3.6.1
          with:
            github_token: ${{ github.token }}
            publish_branch: gh-pages
            publish_dir: MyBlog/bin/Release/net6.0/publish/wwwroot
            allow_empty_commit: false
            keep_files: false
            force_orphan: true